version: '3'

services:
  setter-back:
    container_name: setter-back
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app/
    depends_on:
        - postgres
    networks:
      setter_db_net:
        - ipv4_address: 172.18.0.3

  postgres:
      container_name: setter-postgres
      image: postgres:13
      ports:
        - '5432:5432'
      volumes:
        - ./postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: setter
      networks:
        setter_db_net:
          - ipv4_address: 172.18.0.2
  
  pgadmin:
    container_name: setter-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@setter.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454
    networks:
      setter_db_net:
        - ipv4_address: 172.18.0.3

networks:
  setter_db_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16