"""Create tables used for account management

Revision ID: 18c2ed4939b2
Revises: 
Create Date: 2023-05-30 17:41:06.874096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c2ed4939b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_pessoa_id'), 'pessoa', ['id'], unique=False)
    op.create_table('time',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('naipe', sa.Enum('feminino', 'masculino', 'misto', name='naipetime'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_id'), 'time', ['id'], unique=False)
    op.create_table('administrador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_usuario', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.create_table('atleta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('posicao', sa.Enum('ponteira', 'levantadora', 'central', 'libero', 'oposta', name='posicaoatleta'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('integracao_integra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tipo_pessoa', sa.Enum('administrador', 'atleta', 'tecnico', name='tipopessoa'), nullable=False),
    sa.Column('time_id', sa.UUID(), nullable=True),
    sa.Column('pessoa_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_id', 'pessoa_id', 'tipo_pessoa', name='_time_pessoa_tipo_uc')
    )
    op.create_table('treinador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treinador')
    op.drop_table('integracao_integra')
    op.drop_table('atleta')
    op.drop_table('administrador')
    op.drop_index(op.f('ix_time_id'), table_name='time')
    op.drop_table('time')
    op.drop_index(op.f('ix_pessoa_id'), table_name='pessoa')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
