"""Include event table

Revision ID: 24256295aed0
Revises: fb804d8c6b6e
Create Date: 2023-07-25 16:45:06.874531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24256295aed0'
down_revision = 'fb804d8c6b6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
