"""Add Transacao model

Revision ID: 3374119cfe6d
Revises: 62db66c00551
Create Date: 2023-06-20 18:16:39.309096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3374119cfe6d'
down_revision = '62db66c00551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao_transaciona',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_acontecimento', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('mensalidade', 'despesa', 'ganho', name='tipotransacao'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('time_id', sa.UUID(), nullable=True),
    sa.Column('pessoa_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao_transaciona')
    # ### end Alembic commands ###
