"""Adjust database vulnerabilities

Revision ID: 62db66c00551
Revises: 18c2ed4939b2
Create Date: 2023-06-07 17:39:55.508078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62db66c00551'
down_revision = '18c2ed4939b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'administrador', ['id'])
    op.create_unique_constraint(None, 'atleta', ['id'])
    op.create_unique_constraint(None, 'treinador', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treinador', type_='unique')
    op.drop_constraint(None, 'atleta', type_='unique')
    op.drop_constraint(None, 'administrador', type_='unique')
    # ### end Alembic commands ###
