"""Add name and description to transaction

Revision ID: 975083c914da
Revises: 3374119cfe6d
Create Date: 2023-06-22 18:49:39.156929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975083c914da'
down_revision = '3374119cfe6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacao_transaciona', sa.Column('nome', sa.String(), nullable=False))
    op.add_column('transacao_transaciona', sa.Column('descricao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacao_transaciona', 'descricao')
    op.drop_column('transacao_transaciona', 'nome')
    # ### end Alembic commands ###
